name: check-amazon-inspector
policies:
  - check-amazon-inspector.yaml
  - check-cluster-endpoint.yaml
  - check-cluster-logging.yaml
  - check-cluster-remote-access.yaml
  - check-cluster-rolearn.yaml
  - check-cluster-secrets-encryption.yaml
  - check-cluster-tags.yaml
  - check-immutable-tags-ecr.yaml
  - check-instance-profile-access.yaml
  - check-public-dns.yaml
  - check-vpc-flow-logs.yaml
resources:
  - ./../security_v1alpha1_awsadapterconfig.yaml
results:
  - policy: check-amazon-inspector
    rule: check-amazon-inspector
    resource: test-config
    result: pass
    kind: AWSAdapterConfig
  - policy: check-cluster-endpoint
    rule: check-cluster-endpoint
    resource: test-config
    result: pass
    kind: AWSAdapterConfig
  - policy: check-cluster-logging
    rule: check-cluster-logging
    resource: test-config
    result: skip #
    kind: AWSAdapterConfig
  - policy: check-cluster-remote-access
    rule: check-cluster-remote-access
    resource: test-config
    result: pass
    kind: AWSAdapterConfig
  - policy: check-cluster-rolearn
    rule: check-cluster-rolearn
    resource: test-config
    result: skip #
    kind: AWSAdapterConfig
  - policy: check-cluster-secrets-encryption
    rule: check-cluster-secrets-encryption
    resource: test-config
    result: fail ##
    kind: AWSAdapterConfig
  - policy: check-cluster-tags
    rule: check-department-tag
    resource: test-config
    result: fail ##
    kind: AWSAdapterConfig
  - policy: check-immutable-tags-ecr
    rule: check-immutable-tag
    resource: test-config
    result: skip #
    kind: AWSAdapterConfig
  - policy: check-instance-profile-access
    rule: check-instance-profile-access
    resource: test-config
    result: fail ##
    kind: AWSAdapterConfig
  - policy: check-public-dns
    rule: check-public-dns
    resource: test-config
    result: fail ##
    kind: AWSAdapterConfig
  - policy: check-vpc-flow-logs
    rule: check-vpc-flow-logs
    resource: test-config
    result: pass ##
    kind: AWSAdapterConfig