name: Kyverno Test

on:
  push:
    branches:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: kyverno-aws-adapter
      - name: Clone Enterprise Kyverno
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: nirmata/kyverno
          path: kyverno
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run Kyverno CLI tests
        # run: make kyverno-cli-tests
        run: go run ./cmd/cli/kubectl-kyverno test ../kyverno-aws-adapter -v 3
        working-directory: kyverno